# These are supported funding model platforms

github:[otaboyevsardorbek1]
patreon:[otaboyevsardorbek1]
open_collective: [otaboyevsardorbek1]
ko_fi:[otaboyevsardorbek1]
tidelift:[python]
community_bridge:[otaboyevsardorbek1]
liberapay:[DataMenger]
issuehunt:[otaboyevsardorbek1]
lfx_crowdfunding: [otaboyevsardorbek1]
polar:[otaboyevsardorbek1]
buy_me_a_coffee:[otaboyevsardorbek1]
thanks_dev: [otaboyevsardorbek1]
custom:[https://deepai.org/]
